[project]
name = "zeit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mss>=10.1.0",
    "ollama>=0.6.1",
    "pydantic>=2.12.5",
]
